### ISSUE TITLE
[US] Script Association to Table

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#102]
As an application configurator, I want to attach/associate a script to a certain table, so that eventually, the script can be executed from that table's view.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have | Low                      | 3                    |

## Acceptance Criteria
- Within a given script's settings, a way to associate it to a specific table should be provided.
- The association should be stored in the database, and loaded in the configuration on subsequent access of its settings page 

## Risks
- More dependencies on the VMD

## Tasks
- [ ] Mockups for script association to table in settings menu (if not done already)
- [ ] Create association between a script and a table in the database

## Notes
- This story depends heavily on #101, especially on how the data is being stored/retrieved to/from the database.

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/f87d17d3-09e5-4ca7-9cc7-4dceb75412ae
