### ISSUE TITLE
[US] Execution of Busines Logic Script

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#104]
As an application user, I want to press a button on a table's view so that it executes some business logic script.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Could have |           Medium|             13       |

## Acceptance Criteria
- A way to inject javascript code into the application should be designed
    - In what context would the code run?
    - What data would the persons writing the scripts would be able to use?
    - How could this data be accessed (custom functions?)
    - Would any custom functions access specific things on the application?
    - Etc.
- On confirmation of executing an action from a table's view button, the associated JS code gets:
    - Retrieved from the database
    - Injected into the page
    - Executed

## Risks
- Execution of undesired code in the application
## Tasks
- [x] Clarify any doubts regarding the scripts with the stakeholder.
- [x] TBD

## Notes:
- This story depends on story #103 and all previous stories related to the business logic sidecar.

**Comment by SamRfk** [comment]
![ScriptExecution](https://github.com/WillTrem/UInnovate/assets/78221579/ad340106-2910-4d81-9b12-64a459e11b3d)

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/0cfe96bf-a481-46ea-b0f6-fe6b594fc26d

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
