### ISSUE TITLE
[US] Settings Page For Details/List/Enum view

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#106]
As an application user, I want to be able to toggle the details view and add look-up tables, so that I can modify which tables I want a detail view for, as well as which lookup table I want to be shown.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have |         medium             |        4            |

## Acceptance Criteria
-Ability to see all settings available for list/ enum and details view where they're possibly split into 1 page
-Settings for the Lookup Display table is implemented
## Risks
-Adding complexity in settings component

## Tasks
- [x] Find a way to format all three list settings properly 
- [x] Implement settings page
- [x] Testing

**Comment by MaximeJoanisse** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/92006009/711a5c14-9b7b-462e-8f33-c7c650128c63)
Rough Design for the page

**Comment by TheOrangeDuke** [comment]
Looks good!
Signing off!
