### ISSUE TITLE
[US] Adding Enumeration View

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#18]
As an application user, I want to click an item on the root menu, so that the application displays a Enumeration View of the data contained in that table (selected root menu item).

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have | Medium                     |  8                  |

## Acceptance Criteria
- Ability to display an enumeration view of a certain table from the root menu
- Ability to navigate back to the root menu from the enumeration menu

## Risks
- Uncertainty in how we decide what data should be put in the Enumeration View and what tables we consider candidates for the enum view (vs List View)

## Tasks
- [x] UI Prototypes
- [x] Use case diagram

**Comment by MariaR001** [comment]
![ArchitectureSOEN490- US#18  Enum view](https://github.com/WillTrem/UInnovate/assets/78176331/f538d4fb-6b04-4c41-8f18-447d055099c4)

**Comment by MariaR001** [comment]
![image](https://github.com/WillTrem/UInnovate/assets/78176331/5b4fb888-4c12-4411-910c-9e48c72defd3)

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/96d50649-1577-4470-8949-933d3519bf8b

**Comment by TheOrangeDuke** [comment]
Looks great!
Signing off!
