### ISSUE TITLE
[US] Business Logic Script 

### ISSUE THREAD

**Issue by SamRfk** [WillTrem/UInnovate#183]
As an application user, I want to have a script's description displayed upon hover and to have it editable, so that I can have context behind each script's function.

| MoSCoW      |  Risk               | Story Points  |
| ------ | -------- | -------- |
| Could have | Low | 2 |

## Acceptance Criteria
- A small text box appears on hover when selecting a script from the list view menu, showing the description of the hovered script
- The script's description is editable under the Scripts tab in the Settings page

## Risks
- Updating the code may affect fetching the data of other attributes of a script

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

**Comment by SamRfk** [comment]
https://github.com/WillTrem/UInnovate/assets/78221579/606aa286-4985-45e7-932c-429ff908d573

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
