### ISSUE TITLE
[US] Schema & Data validation

### ISSUE THREAD

**Issue by tsitirides** [WillTrem/UInnovate#21]
As an application developer, I want to have the ability to easily validate the schema and the data in Postgres using the REST API, so that I can ensure the integrity and correctness of the database structure and data.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must have | Medium | 5|

## Acceptance Criteria
- Include checks for data types, relationships, and constraints.
- Provide REST API endpoint for validation that returns detailed results.
## Risks
- Ensuring consistency of data
- Implementation challenges
## Tasks
- [ ] Task **TBD**

**Comment by WillTrem** [comment]
Closing this issue as it is a duplicate of #38
