### ISSUE TITLE
[BUG] List View Pagination

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#232]
## Description of the Bug
The List View pagination displays a specified amount of elements per page, hence it would be to change the default value of elements displayed per page.

## How To Reproduce
Open any table from the app_rentals schema, for example, `company` table will show 20 elements for the page.

## Expected Behavior
The default pagination should be set to 10 elements per page.

## Actual Behavior
The List View pagination is set up to a default of all elements per page.

## Priority
Low

**Comment by MaximeJoanisse** [comment]
video for Stakeholder is in #219's video

**Comment by TheOrangeDuke** [comment]
Signing off - fixed in 219
