### ISSUE TITLE
[BUG] Schema Selector within Settings page

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#233]
## Description of the Bug
In the Settings page, there is no way to change the schema except from the header.

## How To Reproduce
Open the DisplayTab from the Settings page and try to see how you can change the schema without utilizing the Schema selectors via the NavBar

## Expected Behavior
The schema selector should be presented as a dropdown via the Settings page, in DisplayTab, right above the `Tables` header. It should only include the schema's with the app_* prefix.

<img width="1395" alt="Screenshot 2024-02-01 at 8 49 43 PM" src="https://github.com/WillTrem/UInnovate/assets/74876532/21b8f3dd-7991-48c9-ba3a-7d8894e52b62">

## Actual Behavior
It doesn't have a way to select the schema via the Settings page.

## Priority
Medium

**Comment by WillTrem** [comment]
Fixed with PR #250. Closing the issue.
