### ISSUE TITLE
[BUG] ObjMenu Removal

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#234]
## Description of the Bug
The ObjMenu serves as a middle man to display the tables and List View for each schema.

## How To Reproduce
1. Run the app, and stay on the Home page
2. Click on any schema, and notice how you can't see the tables of the schema.
3. Click on ObjMenu and notice how you can finally see the tables

## Expected Behavior
Obj menu should not exist, and to open the tables and List View of any schema, you should be able to directly do it by clicking any of the schema's.

## Actual Behavior
You need to select ObjMenu first to display the tables of any schema

## Priority
High

**Comment by MaximeJoanisse** [comment]
video for Stakeholder is in #219's video

**Comment by TheOrangeDuke** [comment]
Signing off - fixed in 219
