### ISSUE TITLE
[BUG] Stand Alone detail page has no Nav Bar 

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#251]
## Description of the Bug
when the StandAlone detail is enabled, the page of the detail page does not have a NavBar

## How To Reproduce
Go to settings, go on display, pick a table, turn on stand alone detail, on the list view you can now click on a row of that table and the detail page will table your whole screen. Now you can see there is no Navbar

## Expected Behavior
The stand alone detail page needs the NavBar

## Actual Behavior
The stand alone detail page has no NavBar

## Priority
Low

**Comment by MaximeJoanisse** [comment]
video for Stakeholder is in #219's video

**Comment by TheOrangeDuke** [comment]
Signing off - fixed in 219
