### ISSUE TITLE
[BUG] File upload button does not appear on first refresh run

### ISSUE THREAD

**Issue by GuardiansAscend** [WillTrem/UInnovate#260]
## Description of the Bug
File Support doesnt show the button on docker startup

## How To Reproduce
- Reset all the containers, and setup PostGoat from scratch
- On first refresh, the button for files upload is not shown

## Expected Behavior
Button should show immediately

## Actual Behavior
Button doesnt show immediately

## Priority
High

**Comment by SamRfk** [comment]
Bug only reproducible in Kevin's environment because the containers are not running init.sql on his end. It is likely that the .env file is erroneous.
