### ISSUE TITLE
[US] Adding vitest coverage report action for PRs

### ISSUE THREAD

**Issue by MariaR001** [WillTrem/UInnovate#35]
As a platform developer, I want to automatically detect coverage in the CI/CD pipeline, so that I can see it directly in the GitHub Workflow.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |    Medium        |         4           |

## Acceptance Criteria
- Once someone opens a new pull request, the coverage report action should be triggered as a comment.

## Risks
-  Code coverage reports may require maintenance as your codebase evolves. 
- High code coverage doesn't necessarily equate to a high-quality test suite. (tests need to be well-written, maintainable, and accurately reflect the behavior of your code.)
- Slow Build Times

## Tasks
- [x] Add workflow file & configure it to display code coverage as a comment for PRs

**Comment by MariaR001** [comment]
https://github.com/WillTrem/UInnovate/assets/78176331/eefd4560-7be8-43f1-8048-026e618a8813

@AfandiM & @WillTrem also contributed.

**Comment by TheOrangeDuke** [comment]
Looks good! Super nice work on the coverage report! Signing off!

**Comment by adivardhan1000** [comment]
I can't view the video.

**Comment by MariaR001** [comment]
> I can't view the video. @adivardhan1000  I reuploaded it


https://github.com/WillTrem/UInnovate/assets/78176331/46fe929d-e2c6-4d85-badf-7353a6250a6c
