### ISSUE TITLE
[BUG] Coverage files are being tracked by git

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/UInnovate#49]
## Description of the Bug
When running the command `npm run coverage`, the generated files are being tracked by git, as if changes had been made

## How To Reproduce
Run `npm run coverage` inside the UInnovateApp directory

## Expected Behavior
The generated files should not be added as changes from git's perspective

## Actual Behavior
Files generated from the coverage report are being tracked by git
![image](https://github.com/WillTrem/UInnovate/assets/64431699/a78e7450-abce-4545-8cca-6363f48e23cb)

## Priority
Low

**Comment by MariaR001** [comment]
pr #50 merged
