### ISSUE TITLE
[US] Set up MkDocs 

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#57]
As a platform developer, I want to be able to look up documentation for different aspects of the platform, so that I can understand my tasks better and have an easier time working with the apps.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Medium                     |   3                 |

## Acceptance Criteria
- Functional documentation website
- Functional generation process
- Integrated with docker

## Risks
- Integration with repository failing
- Integration with docker / into docker containers

## Tasks
- [x] Set up MKdocs in project
- [x] Integrating docker to run mkdocs

## Note
**This US has a dependency with US #62, because one of its tasks is to document regarding Use Case 1. Therefore, we must set up the MkDocs(this US) first to be able to start documenting. Please coordinate with the other assignee.**

## Useful Links 
https://www.mkdocs.org/
https://hub.docker.com/r/polinux/mkdocs

**Comment by MariaR001** [comment]
https://github.com/WillTrem/UInnovate/assets/78176331/4f5888cb-9cf2-49f3-ba21-11322f9cb9b6

**Comment by TheOrangeDuke** [comment]
Looks good! Signing off!
