### ISSUE TITLE
[US] Data Displayed in the List View

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#59]
As an application user, I want the data from the database to be displayed in the list view, in the appropriate table and columns, so that I can visualize all the data of my tables directly from the List View Display.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must |       Medium           |   5        |

## Acceptance Criteria
- Ability to display the data from the database in the appropriate table and columns in the List View.

## Risks
- Adding complexity to the Virtual Model Definition

## Tasks
- [x]  VMD can retrieve the data
- [x] Data is frontend 
- [x] Unit testing

**Comment by MaximeJoanisse** [comment]
https://github.com/WillTrem/UInnovate/assets/92006009/99aa9514-70c8-4bd2-a896-af8d75263cf7

**Comment by MaximeJoanisse** [comment]
Roughly what was followed for design

![image](https://github.com/WillTrem/UInnovate/assets/92006009/2ca88c33-c0ff-4f33-8ced-90242e51fe3a)

**Comment by TheOrangeDuke** [comment]
Looks great!
Signing off!
