### ISSUE TITLE
[US] Export configuration as JSON

### ISSUE THREAD

**Issue by AfandiM** [WillTrem/UInnovate#61]
Export as JSON: As an application configurator, I want to click on a button that will export a JSON representation of the configuration, so that I can easily save and migrate configuration options.

Import JSON functionality (Part 2) --> Iteration 5 (dependent on #58)
As an application configurator, I want to be able to import configuration options from a JSON, so that I can easily migrate and restore configuration options. 

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should have |    Medium                  |    4                |

## Acceptance Criteria
- Have an export JSON file with appropriate data values and types
- Aggregate meta.appconfig_values & meta.appconfig_properties to SQL procedure that can successfully be executed
## Risks
- Improper JSON file format (format-checking)
- Accessing appropriate headers
- Pushing new configuration options to database (complex) -> Iteration 5
## Tasks
- [x] Create function or stored proc in meta schema to aggregate relevant config tables
- [x] Create exec script to run the procedure and export JSON file of current config settings

**Comment by Alexicazana** [comment]
Export to JSON script created; issues with access to the config properties (working on it)
![Screenshot 2023-11-13 at 4 39 36 PM](https://github.com/WillTrem/UInnovate/assets/55753055/8d5333e4-cd8e-407d-9407-99548ab1e41c)

**Comment by Alexicazana** [comment]
TODO: 
make sure the PostgREST endpoint is properly written (!!);
add documentation for running export script;
create import config json functionality;
create simple UI element for box drop off of .json import config;

**Comment by Alexicazana** [comment]
![Uploading Screenshot 2023-11-14 at 10.32.50 PM.png…]()

**Comment by Alexicazana** [comment]
![Screenshot 2023-11-14 at 10 32 50 PM](https://github.com/WillTrem/UInnovate/assets/55753055/25be9184-a496-471a-a122-33fc034834c8)

**Comment by Alexicazana** [comment]
![Screenshot 2023-11-14 at 10 46 19 PM](https://github.com/WillTrem/UInnovate/assets/55753055/98849b4d-05b6-44a2-9019-eb07f03c48a7)

**Comment by Alexicazana** [comment]
Created shell script to execute the stored procedure function

![Screenshot 2023-11-14 at 10 48 00 PM](https://github.com/WillTrem/UInnovate/assets/55753055/6e1cf599-dbbe-41f8-95af-5d9abd9e3fee)

**Comment by Alexicazana** [comment]
Created Upload JSON configuration file button on the Settings page

![Screenshot 2023-11-14 at 11 18 01 PM](https://github.com/WillTrem/UInnovate/assets/55753055/044459c8-53e8-4608-a618-8b1b993976bd)

**Comment by Alexicazana** [comment]
https://github.com/WillTrem/UInnovate/assets/55753055/d7e56aee-d7f7-4849-a55d-556599e7b13d

**Comment by TheOrangeDuke** [comment]
Looks good!
Signing off!
