### ISSUE TITLE
[US] Navbar Schema Customization

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#69]
## US for new teammate during Release 1
As an application user, I want to be able to select which schema (Meta/Application) to display from the navigation bar, so that it displays the proper tables. 

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |           Low           |          3         |

## Acceptance Criteria
- Ability to select the desired schema from the navigation bar. (Meta/Application)
- On schema selection, the user should be able to see the tables from the desired schema.

## Risks
Adding complexity to the Virtual Model Definition

## Tasks
- [x] UI mockup
- [x] Adding the group-buttons for "Meta" and "Application" on the navigation bar, with the proper logic to display the schema

## Optional Task 
**_Optional for this US because it was created and assigned a few days before Release 1_ to a new teammate during the onboarding**
In the Settings page, in the tab "General", having the option to customize the buttons representing the schema selection from the navbar either as a dropdown or as a group-button(default value).

## Note
**This user story is related to US #59, please coordinate with the other assignee.**

**Comment by lyubageorgieva** [comment]
## Quick Sketch 
![image](https://github.com/WillTrem/UInnovate/assets/74876532/1a7b3194-92f1-4a67-91db-a4f7cbd736ee)

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/779a038a-05f6-4fc2-a5be-10b3f76c0786

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/623b9bac-d78a-4bf2-82e6-e822bca24ca9

**Comment by witnick** [comment]
https://github.com/WillTrem/UInnovate/assets/10947924/14d8f333-3b54-4092-9879-7283a652bb21

**Comment by TheOrangeDuke** [comment]
Looks good, signing off!
