### ISSUE TITLE
[US] Improvement of Shell Scripts 

### ISSUE THREAD

**Issue by lyubageorgieva** [WillTrem/UInnovate#87]
As a platform developer, I want to improve the shell script that does database manipulations so that I can also export configs (overwrite when needed) and to have one common way to call all of the shell scripts (because currently we have multiple shell scripts).

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Should |           Low           |             2      |

## Acceptance Criteria
- Ability to export configs
- Ability to have a common way to call all of the shell scripts

## Risks
TBD

## Tasks
- [x] Meet with the stakeholder
- [x] Complete the tasks of the US

## Additional notes
<img width="371" alt="image" src="https://github.com/WillTrem/UInnovate/assets/74876532/f883fbea-a9e0-4e9f-b695-776158aa452b">

**Comment by TheOrangeDuke** [comment]
Looks good to me! 
signing off!
